name: docker build for quay.io

on:
  push:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker_build.yml'

# https://github.com/lkiesow/automated-quay.io-deployment/
jobs:
  build:
    name: Webhook
    runs-on: ubuntu-latest
    steps:
      # https://github.com/VincentRouvreau/automated-quay.io-deployment/blob/master/README.md
      - name: Webhook on quay.io
        run: |
          echo ${{ secrets.POUET }}
          curl -s https://raw.githubusercontent.com/VincentRouvreau/automated-quay.io-deployment/master/deploy-on-quay | sh
